// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFU9lORRpxCLfD9EAdrVAC4Gx0LgVHufk',
    appId: '1:388802963138:web:c16bef05af260c4ce0bd5b',
    messagingSenderId: '388802963138',
    projectId: 'dal-ani',
    authDomain: 'dal-ani.firebaseapp.com',
    databaseURL: 'https://dal-ani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dal-ani.firebasestorage.app',
    measurementId: 'G-LVZT5SS0C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0LLL3XBvewNJ-reemFqMpTJbmRVReSgI',
    appId: '1:388802963138:android:5e8a489917dd01a9e0bd5b',
    messagingSenderId: '388802963138',
    projectId: 'dal-ani',
    databaseURL: 'https://dal-ani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dal-ani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhyLzQEig-QE3K33B3TCsJaUv8FlPD9as',
    appId: '1:388802963138:ios:2be04e5df64a8966e0bd5b',
    messagingSenderId: '388802963138',
    projectId: 'dal-ani',
    databaseURL: 'https://dal-ani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dal-ani.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhyLzQEig-QE3K33B3TCsJaUv8FlPD9as',
    appId: '1:388802963138:ios:2be04e5df64a8966e0bd5b',
    messagingSenderId: '388802963138',
    projectId: 'dal-ani',
    databaseURL: 'https://dal-ani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dal-ani.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFU9lORRpxCLfD9EAdrVAC4Gx0LgVHufk',
    appId: '1:388802963138:web:371180dd3ddd1dc5e0bd5b',
    messagingSenderId: '388802963138',
    projectId: 'dal-ani',
    authDomain: 'dal-ani.firebaseapp.com',
    databaseURL: 'https://dal-ani-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dal-ani.firebasestorage.app',
    measurementId: 'G-QD4FLEMYS9',
  );
}
